version: "3"
services:
  gitbook_wiki:
    build:
      context: .
      dockerfile: ./Dockerfile-gitbook
    container_name: gitbook
    hostname: gitbook
    restart: always
    ports:
      - "4000:4000"
      - "4001:4001"
      - "35729:35729"
    volumes:
      - .:/gitbook
    environment:
      BOOK_URL: https://github.com/threeMango/doc.git
    command: ['/gitbook/start.sh']